In [1]:
import h2o
from h2o.estimators.gbm import H2OGradientBoostingEstimator
h2o.init()

# import the cars dataset:
# this dataset is used to classify whether or not a car is economical based on
# the car's displacement, power, weight, and acceleration, and the year it was made
cars = h2o.import_file("https://s3.amazonaws.com/h2o-public-test-data/smalldata/junit/cars_20mpg.csv")

# set the predictor names and the response column name
predictors = ["displacement","power","weight","acceleration","year"]
response = "cylinders"

# split into train and validation sets
train, valid = cars.split_frame(ratios = [.8], seed = 1234)

# train a GBM model
cars_gbm = H2OGradientBoostingEstimator(distribution = "poisson", seed = 1234)
cars_gbm.train(x = predictors,
               y = response,
               training_frame = train,
               validation_frame = valid)

# retrieve the model performance
perf = cars_gbm.model_performance(valid)
perf

Checking whether there is an H2O instance running at http://localhost:54321 ..... not found.
Attempting to start a local H2O server...
  Java Version: openjdk version "11.0.8" 2020-07-14; OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10); OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.8+10, mixed mode)
  Starting server from /home/pzhao28/anaconda3/lib/python3.7/site-packages/h2o/backend/bin/h2o.jar
  Ice root: /tmp/tmp_ke5w2ql
  JVM stdout: /tmp/tmp_ke5w2ql/h2o_pzhao28_started_from_python.out
  JVM stderr: /tmp/tmp_ke5w2ql/h2o_pzhao28_started_from_python.err
  Server is running at http://127.0.0.1:54321
Connecting to H2O server at http://127.0.0.1:54321 ... successful.

--------------------------  ------------------------------------------------------------------
H2O_cluster_uptime:         01 secs
H2O_cluster_timezone:       America/Phoenix
H2O_data_parsing_timezone:  UTC
H2O_cluster_version:        3.30.1.3
H2O_cluster_version_age:    24 days
H2O_cluster_name:           H2O_from_python_pzhao28_1whpm1
H2O_cluster_total_nodes:    1
H2O_cluster_free_memory:    7.836 Gb
H2O_cluster_total_cores:    8
H2O_cluster_allowed_cores:  8
H2O_cluster_status:         accepting new members, healthy
H2O_connection_url:         http://127.0.0.1:54321
H2O_connection_proxy:       {"http": null, "https": null}
H2O_internal_security:      False
H2O_API_Extensions:         Amazon S3, XGBoost, Algos, AutoML, Core V3, TargetEncoder, Core V4
Python_version:             3.7.4 final
--------------------------  ------------------------------------------------------------------

Parse progress: |█████████████████████████████████████████████████████████| 100%
gbm Model Build progress: |███████████████████████████████████████████████| 100%

ModelMetricsRegression: gbm
** Reported on test data. **

MSE: 0.03769791966551617
RMSE: 0.19415952118172358
MAE: 0.07947861719967757
RMSLE: 0.03359130162278705
Mean Residual Deviance: -9.918300985300526

In [2]:
valid

name,economy,cylinders,displacement,power,weight,acceleration,year,economy_20mpg
AMC Concord DL 6,20.2,6,232,90,3265,18.2,79,1
AMC Gremlin,19,6,232,100,2634,13,71,0
AMC Hornet,18,6,232,100,2945,16,73,0
AMC Matador (Wagon),14,8,304,150,4257,15.5,74,0
AMC Matador (Wagon),15,8,304,150,3892,12.5,72,0
AMC Matador,14,8,304,150,3672,11.5,73,0
AMC Matador,15,6,258,110,3730,19,75,0
AMC Matador,15.5,8,304,120,3962,13.9,76,0
AMC Rebel SST (Wagon),nan,8,360,175,3850,11,70,nan
Audi 100 LS,20,4,114,91,2582,14,73,0

In [4]:
train.head(100)

name,economy,cylinders,displacement,power,weight,acceleration,year,economy_20mpg
AMC Ambassador Brougham,13,8,360,175,3821,11,73,0
AMC Ambassador DPL,15,8,390,190,3850,8.5,70,0
AMC Ambassador SST,17,8,304,150,3672,11.5,72,0
AMC Concord DL,18.1,6,258,120,3410,15.1,78,0
AMC Concord DL,23,4,151,nan,3035,20.5,82,1
AMC Concord,19.4,6,232,90,3210,17.2,78,0
AMC Concord,24.3,4,151,90,3003,20.1,80,1
AMC Gremlin,18,6,232,100,2789,15,73,0
AMC Gremlin,20,6,232,100,2914,16,75,0
AMC Gremlin,21,6,199,90,2648,15,70,1
AMC Hornet Sportabout (Wagon),18,6,258,110,2962,13.5,71,0
AMC Hornet,18,6,199,97,2774,15.5,70,0
AMC Hornet,19,6,232,100,2901,16,74,0
AMC Hornet,22.5,6,232,90,3085,17.6,76,1
AMC Matador,16,6,258,110,3632,18,74,0
AMC Matador,18,6,232,100,3288,15.5,71,0
AMC Pacer D/L,17.5,6,258,95,3193,17.8,76,0
AMC Pacer,19,6,232,90,3211,17,75,0
AMC Rebel SST,16,8,304,150,3433,12,70,0
AMC Spirit DL,27.4,4,121,80,2670,15,79,1
Audi 100 LS,23,4,115,95,2694,15,75,1
Audi 100 LS,24,4,107,90,2430,14.5,70,1
Audi 5000,20.3,5,131,103,2830,15.9,78,1
Audi Fox,29,4,98,83,2219,16.5,74,1
BMW 2002,26,4,121,113,2234,12.5,70,1
BMW 320i,21.5,4,121,110,2600,12.8,77,1
Buick Century Limited,25,6,181,110,2945,16.4,82,1
Buick Century Special,20.6,6,231,105,3380,15.8,78,1
Buick Century,17,6,231,110,3907,21,75,0
Buick Century,22.4,6,231,110,3415,15.8,81,1
Buick Electra 225 Custom,12,8,455,225,4951,11,73,0
Buick Estate Wagon (Wagon),14,8,455,225,3086,10,70,0
Buick Estate Wagon (Wagon),16.9,8,350,155,4360,14.9,79,0
Buick Lesabre Custom,13,8,350,155,4502,13.5,72,0
Buick Opel Isuzu Deluxe,30,4,111,80,2155,14.8,77,1
Buick Regal Sport Coupe (Turbo),17.7,6,231,165,3445,13.4,78,0
Buick Skyhawk,21,6,231,110,3039,15,75,1
Buick Skylark Limited,28.4,4,151,90,2670,16,79,1
Buick Skylark,20.5,6,231,105,3425,16.9,77,1
Buick Skylark,26.6,4,151,84,2635,16.4,81,1
Chevroelt Chevelle Malibu,16,6,250,105,3897,18.5,75,0
Chevrolet Bel Air,15,8,350,145,4440,14,75,0
Chevrolet Camaro,27,4,151,90,2950,17.3,82,1
Chevrolet Caprice Classic,17,8,305,130,3840,15.4,79,0
Chevrolet Caprice Classic,17.5,8,305,145,3880,12.5,77,0
Chevrolet Cavalier 2-Door,34,4,112,88,2395,18,82,1
Chevrolet Cavalier,28,4,112,88,2605,19.6,82,1
Chevrolet Chevelle Concours (Wagon),13,8,307,130,4098,14,72,0
Chevrolet Chevelle Malibu Classic,16,6,250,100,3781,17,74,0
Chevrolet Chevelle Malibu Classic,17.5,8,305,140,4215,13,76,0
Chevrolet Chevelle Malibu,17,6,250,100,3329,15.5,71,0
Chevrolet Chevelle Malibu,18,8,307,130,3504,12,70,0
Chevrolet Chevette,29,4,85,52,2035,22.2,76,1
Chevrolet Chevette,30,4,98,68,2155,16.5,78,1
Chevrolet Chevette,30.5,4,98,63,2051,17,77,1
Chevrolet Chevette,32.1,4,98,70,2120,15.5,80,1
Chevrolet Citation,23.5,6,173,110,2725,12.6,81,1
Chevrolet Citation,28,4,151,90,2678,16.5,80,1
Chevrolet Citation,28.8,6,173,115,2595,11.3,79,1
Chevrolet Concours,17.5,6,250,110,3520,16.4,77,0
Chevrolet Impala,11,8,400,150,4997,14,73,0
Chevrolet Impala,13,8,350,165,4274,12,72,0
Chevrolet Impala,14,8,350,165,4209,12,71,0
Chevrolet Malibu Classic (Wagon),19.2,8,267,125,3605,15,79,0
Chevrolet Malibu,13,8,350,145,3988,13,73,0
Chevrolet Malibu,20.5,6,200,95,3155,18.2,78,1
Chevrolet Monte Carlo Landau,15.5,8,350,170,4165,11.4,77,0
Chevrolet Monte Carlo S,15,8,350,145,4082,13,73,0
Chevrolet Monza 2+2,20,8,262,110,3221,13.5,75,0
Chevrolet Nova Custom,16,6,250,100,3278,18,73,0
Chevrolet Nova,15,6,250,100,3336,17,74,0
Chevrolet Nova,18,6,250,105,3459,16,75,0
Chevrolet Nova,22,6,250,105,3353,14.5,76,1
Chevrolet Vega (Wagon),22,4,140,72,2408,19,71,1
Chevrolet Vega 2300,28,4,140,90,2264,15.5,71,1
Chevrolet Vega,21,4,140,72,2401,19.5,73,1
Chevrolet Vega,25,4,140,75,2542,17,74,1
Chevrolet Woody,24.5,4,98,60,2164,22.1,76,1
Chevy C10,13,8,350,145,4055,12,76,0
Chevy C20,10,8,307,200,4376,15,70,0
Chevy S-10,31,4,119,82,2720,19.4,82,1
Chrysler Cordoba,15.5,8,400,190,4325,12.2,77,0
Chrysler Lebaron Medallion,26,4,156,92,2585,14.5,82,1
Chrysler Lebaron Salon,17.6,6,225,85,3465,16.6,81,0
Chrysler Lebaron Town & Country (Wagon),18.5,8,360,150,3940,13,79,0
Chrysler New Yorker Brougham,13,8,440,215,4735,11,73,0
Citroen DS-21 Pallas,nan,4,133,115,3090,17.5,70,nan
Datsun 1200,35,4,72,69,1613,18,71,1
Datsun 200SX,23.9,4,119,97,2405,14.9,78,1
Datsun 200SX,32.9,4,119,100,2615,14.8,81,1
Datsun 210,31.8,4,85,65,2020,19.2,79,1
Datsun 210,37,4,85,65,1975,19.4,81,1
Datsun 210,40.8,4,85,65,2110,19.2,80,1
Datsun 280ZX,32.7,6,168,132,2910,11.4,80,1
Datsun 310,37.2,4,86,65,2019,16.4,80,1
Datsun 510 (Wagon),28,4,97,92,2288,17,72,1
Datsun 510 Hatchback,37,4,119,92,2434,15,80,1
Datsun 510,27.2,4,119,97,2300,14.7,78,1
Datsun 610,22,4,108,94,2379,16.5,73,1
Datsun 710,24,4,119,97,2545,17,75,1

In [8]:
pred

predict,p0,p1,cal_p0,cal_p1
1,0.542275,0.457725,0.760534,0.239466
0,0.566532,0.433468,0.788617,0.211383
0,0.653978,0.346022,0.869554,0.130446
0,0.965854,0.0341463,0.981422,0.0185779
0,0.99,0.01,0.98413,0.0158705
0,0.99,0.01,0.98413,0.0158705
0,0.891425,0.108575,0.96991,0.0300896
0,0.88,0.12,0.967617,0.0323833
0,1,0,0.985134,0.0148665
1,0.0948147,0.905185,0.140117,0.859883

In [9]:
cars

name,economy,cylinders,displacement,power,weight,acceleration,year,economy_20mpg
AMC Ambassador Brougham,13,8,360,175,3821,11,73,0
AMC Ambassador DPL,15,8,390,190,3850,8.5,70,0
AMC Ambassador SST,17,8,304,150,3672,11.5,72,0
AMC Concord DL 6,20.2,6,232,90,3265,18.2,79,1
AMC Concord DL,18.1,6,258,120,3410,15.1,78,0
AMC Concord DL,23,4,151,nan,3035,20.5,82,1
AMC Concord,19.4,6,232,90,3210,17.2,78,0
AMC Concord,24.3,4,151,90,3003,20.1,80,1
AMC Gremlin,18,6,232,100,2789,15,73,0
AMC Gremlin,19,6,232,100,2634,13,71,0

In [10]:
cars_drf

Model Details
=============
H2ORandomForestEstimator :  Distributed Random Forest
Model Key:  DRF_model_python_1603473007745_1


Model Summary:

,,number_of_trees,number_of_internal_trees,model_size_in_bytes,min_depth,max_depth,mean_depth,min_leaves,max_leaves,mean_leaves
0,,10.0,20.0,3198.0,3.0,5.0,4.1,6.0,9.0,8.15

ModelMetricsBinomial: drf
** Reported on train data. **

MSE: 0.07167425726941093
RMSE: 0.2677204834700007
LogLoss: 0.6277394507856711
Mean Per-Class Error: 0.0833475588938204
AUC: 0.9521807784226699
AUCPR: 0.9610198834906681
Gini: 0.9043615568453398

Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.6030516722550698:

              0      1   Error           Rate
0      0  107.0    9.0  0.0776    (9.0/116.0)
1      1   18.0  184.0  0.0891   (18.0/202.0)
2  Total  125.0  193.0  0.0849   (27.0/318.0)

Maximum Metrics: Maximum metrics at their respective thresholds

                         metric  threshold       value    idx
0                        max f1   0.603052    0.931646   63.0
1                        max f2   0.234491    0.963391   99.0
2                  max f0point5   0.603052    0.944559   63.0
3                  max accuracy   0.603052    0.915094   63.0
4                 max precision   0.982456    0.975806    3.0
5                    max recall   0.000000    1.000000  132.0
6               max specificity   1.000000    0.974138    0.0
7              max absolute_mcc   0.603052    0.821249   63.0
8    max min_per_class_accuracy   0.603052    0.910891   63.0
9   max mean_per_class_accuracy   0.603052    0.916652   63.0
10                      max tns   1.000000  113.000000    0.0
11                      max fns   1.000000   88.000000    0.0
12                      max fps   0.000000  116.000000  132.0
13                      max tps   0.000000  202.000000  132.0
14                      max tnr   1.000000    0.974138    0.0
15                      max fnr   1.000000    0.435644    0.0
16                      max fpr   0.000000    1.000000  132.0
17                      max tpr   0.000000    1.000000  132.0

Gains/Lift Table: Avg response rate: 62.77 %, avg score: 62.10 %

,group,cumulative_data_fraction,lower_threshold,lift,cumulative_lift,response_rate,score,cumulative_response_rate,cumulative_score,capture_rate,cumulative_capture_rate,gain,cumulative_gain,kolmogorov_smirnov
0,1,0.360000,1.000000,1.552288,1.552288,0.974359,1.000000,0.974359,1.000000,0.558824,0.558824,55.228758,55.228758,0.534030
1,2,0.406154,0.957125,1.486928,1.544860,0.933333,0.976940,0.969697,0.997380,0.068627,0.627451,48.692810,54.486037,0.594393
2,3,0.507692,0.854396,1.448307,1.525550,0.909091,0.901629,0.957576,0.978230,0.147059,0.774510,44.830660,52.554961,0.716659
3,4,0.609231,0.532670,1.303476,1.488537,0.818182,0.726742,0.934343,0.936315,0.132353,0.906863,30.347594,48.853733,0.799425
4,5,0.710769,0.223336,0.724153,1.379340,0.454545,0.373025,0.865801,0.855845,0.073529,0.980392,-27.584670,37.933961,0.724194
5,6,0.812308,0.041469,0.048277,1.212957,0.030303,0.116022,0.761364,0.763367,0.004902,0.985294,-95.172311,21.295677,0.464633
6,7,1.000000,0.000000,0.078351,1.000000,0.049180,0.004765,0.627692,0.620983,0.014706,1.000000,-92.164899,0.000000,0.000000

ModelMetricsBinomial: drf
** Reported on validation data. **

MSE: 0.0782562709016502
RMSE: 0.2797432231558974
LogLoss: 0.2382614928127087
Mean Per-Class Error: 0.07880844645550522
AUC: 0.9751131221719458
AUCPR: 0.9730927260518765
Gini: 0.9502262443438916

Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.45772475691013736:

             0     1   Error         Rate
0      0  34.0   5.0  0.1282   (5.0/39.0)
1      1   1.0  33.0  0.0294   (1.0/34.0)
2  Total  35.0  38.0  0.0822   (6.0/73.0)

Maximum Metrics: Maximum metrics at their respective thresholds

                         metric  threshold      value   idx
0                        max f1   0.457725   0.916667  23.0
1                        max f2   0.457725   0.948276  23.0
2                  max f0point5   0.940605   0.942029  11.0
3                  max accuracy   0.744772   0.917808  21.0
4                 max precision   1.000000   1.000000   0.0
5                    max recall   0.122951   1.000000  29.0
6               max specificity   1.000000   1.000000   0.0
7              max absolute_mcc   0.457725   0.841115  23.0
8    max min_per_class_accuracy   0.754049   0.897436  20.0
9   max mean_per_class_accuracy   0.457725   0.921192  23.0
10                      max tns   1.000000  39.000000   0.0
11                      max fns   1.000000  21.000000   0.0
12                      max fps   0.000000  39.000000  39.0
13                      max tps   0.122951  34.000000  29.0
14                      max tnr   1.000000   1.000000   0.0
15                      max fnr   1.000000   0.617647   0.0
16                      max fpr   0.000000   1.000000  39.0
17                      max tpr   0.122951   1.000000  29.0

Gains/Lift Table: Avg response rate: 46.58 %, avg score: 52.02 %

,group,cumulative_data_fraction,lower_threshold,lift,cumulative_lift,response_rate,score,cumulative_response_rate,cumulative_score,capture_rate,cumulative_capture_rate,gain,cumulative_gain,kolmogorov_smirnov
0,1,0.178082,1.000000,2.147059,2.147059,1.000000,1.000000,1.000000,1.000000,0.382353,0.382353,114.705882,114.705882,0.382353
1,2,0.232877,0.984737,2.147059,2.147059,1.000000,0.987368,1.000000,0.997028,0.117647,0.500000,114.705882,114.705882,0.500000
2,3,0.315068,0.965494,2.147059,2.147059,1.000000,0.975155,1.000000,0.991322,0.176471,0.676471,114.705882,114.705882,0.676471
3,4,0.424658,0.892045,1.610294,2.008539,0.750000,0.919187,0.935484,0.972706,0.176471,0.852941,61.029412,100.853890,0.801659
4,5,0.520548,0.445596,1.226891,1.864551,0.571429,0.741243,0.868421,0.930068,0.117647,0.970588,22.689076,86.455108,0.842383
5,6,0.630137,0.109083,0.268382,1.586957,0.125000,0.283031,0.739130,0.817540,0.029412,1.000000,-73.161765,58.695652,0.692308
6,7,0.753425,0.020000,0.000000,1.327273,0.000000,0.038443,0.618182,0.690052,0.000000,1.000000,-100.000000,32.727273,0.461538
7,8,1.000000,0.000000,0.000000,1.000000,0.000000,0.001111,0.465753,0.520176,0.000000,1.000000,-100.000000,0.000000,0.000000

Scoring History:

,,timestamp,duration,number_of_trees,training_rmse,training_logloss,training_auc,training_pr_auc,training_lift,training_classification_error,validation_rmse,validation_logloss,validation_auc,validation_pr_auc,validation_lift,validation_classification_error
0,,2020-10-23 10:13:51,0.025 sec,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,,2020-10-23 10:13:52,0.207 sec,1.0,0.288584,0.783658,0.941891,0.956334,1.542561,0.112069,0.294711,1.545161,0.940045,0.911556,2.003922,0.123288
2,,2020-10-23 10:13:52,0.253 sec,2.0,0.296112,0.926112,0.939702,0.955762,1.544368,0.111111,0.292196,1.127464,0.949849,0.931028,2.044818,0.095890
3,,2020-10-23 10:13:52,0.278 sec,3.0,0.304032,0.954671,0.933073,0.949096,1.535727,0.120172,0.287145,1.109562,0.950226,0.931190,2.039706,0.082192
4,,2020-10-23 10:13:52,0.307 sec,4.0,0.285987,0.831506,0.941532,0.954073,1.541746,0.106618,0.277595,0.678367,0.957014,0.958812,2.147059,0.082192
5,,2020-10-23 10:13:52,0.328 sec,5.0,0.283599,0.789191,0.943774,0.955049,1.543738,0.099315,0.284810,0.678507,0.957391,0.961853,2.147059,0.082192
6,,2020-10-23 10:13:52,0.351 sec,6.0,0.282526,0.775605,0.942424,0.955033,1.544118,0.100000,0.277325,0.232574,0.975867,0.976328,2.147059,0.068493
7,,2020-10-23 10:13:52,0.373 sec,7.0,0.279308,0.749403,0.945751,0.955457,1.543738,0.096154,0.275761,0.231754,0.975867,0.976510,2.147059,0.068493
8,,2020-10-23 10:13:52,0.395 sec,8.0,0.275068,0.635871,0.950463,0.960344,1.553309,0.094637,0.278643,0.234734,0.971342,0.969663,2.147059,0.082192
9,,2020-10-23 10:13:52,0.413 sec,9.0,0.268175,0.626433,0.952650,0.961388,1.552634,0.084906,0.278654,0.235700,0.973605,0.972097,2.147059,0.082192
10,,2020-10-23 10:13:52,0.433 sec,10.0,0.267720,0.627739,0.952181,0.961020,1.552288,0.084906,0.279743,0.238261,0.975113,0.973093,2.147059,0.082192

Variable Importances:

       variable  relative_importance  scaled_importance  percentage
0        weight           440.754974           1.000000    0.421418
1  displacement           383.773346           0.870718    0.366936
2         power           155.198761           0.352120    0.148390
3  acceleration            39.571045           0.089780    0.037835
4          year            26.587412           0.060322    0.025421

In [14]:
cars_drf.rmse(valid=True)

0.2797432231558974